### ISSUE TITLE
It would be great if this was on conda-forge

### ISSUE THREAD

**Issue by bedaro** [leonhard-s/Py2DM#7]
I'm starting a conda environment I wish to distribute to others in my group, and the one package that's not available in any Anaconda channel is this one. I'm willing to bite the bullet and become the conda-forge maintainer, but since it's your project I thought you should at least get a heads up (or the opportunity to do it yourself).

**Comment by leonhard-s** [comment]
Hi, thank you for the suggestion. I have rather limited experience with the Anaconda packaging system or the conda-forge workflow, so I am more than happy to relinquish the maintainer role to someone who uses it more regularly.

**Comment by bedaro** [comment]
Finally got around to this. Pull request created https://github.com/conda-forge/staged-recipes/pull/18788

**Comment by leonhard-s** [comment]
Closing as the conda-forge recipe has been added - thanks again for your work @​bedaro!
